data:
  raw_data_path: data/raw/raw_scraped.csv
  prp_data_path: data/processed/prp_data.csv


scraper:
  args_dict_path: args_dict.json



  

base:
  project: activity_recognition_project
  target_col: label
  random_state: 45

data_source:
  source_dir: data/external

data_paths:
  raw_dataset_csv: data/raw/master_dataset.csv

preprocess:
  cols_to_remove: ["# Columns: time"]

features_schema_path: tests/features_schema.json


split_data:
  train_path: data/processed/train_dataset.csv
  test_path: data/processed/test_dataset.csv
  test_size: 0.2

algorithm_name: 
  Random Forest Classifier

estimators:
  RandomForestClassifier:
    params:
      n_estimators: 51
      criterion: gini
 
artifact_dir: saved_artifacts
production_model_dir: production_model

reports:
  params: reports/params.json
  scores: reports/scores.json

scaler: saved_artifacts/std_scaler.pkl
label_encoder: saved_artifacts/label_encoder.pkl

webapp_model: production_model/rfc_model.pkl

mlflow_config:
  artifact_dir: mlflow_artifacts
  experiment_name: Random Forest Classification
  run_name: mlops
  registered_model_name: RandomForestClassifier
  remote_server_uri: http://127.5.5.5:1234